# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1al0gA7YGGjedj97Xbphb21-Qb-YtxOcj
"""

# Install required libraries
!pip install sentence-transformers matplotlib seaborn numpy pandas

# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

print("Libraries imported successfully!")

# Load the pre-trained sentence transformer model
print("Loading model...")
model = SentenceTransformer('all-MiniLM-L6-v2')
print("Model loaded successfully!")
print(f"Model name: {model.get_sentence_embedding_dimension()} dimensions")

# Define 10 sentences across 3 topics (Cricket, Cooking, Cybersecurity)

sentences = [
    # Cricket (3 sentences)
    "The batsman hit a six over long-on to win the match.",
    "The bowler took three wickets in one over with excellent yorkers.",
    "The fielder took a spectacular catch at the boundary line.",

    # Cooking (4 sentences - to meet minimum 3)
    "Chef carefully chopped fresh vegetables for the vegetable soup.",
    "The cake was baked at 180 degrees for thirty minutes.",
    "She added garlic and onions to the hot pan for flavor.",
    "The pasta needs to be boiled until it becomes al dente.",

    # Cybersecurity (3 sentences)
    "The company implemented multi-factor authentication to prevent unauthorized access.",
    "Security analysts detected a ransomware attack on the network.",
    "Encryption protocols ensure data remains secure during transmission."
]

# Verify we have 10 sentences
print(f"Number of sentences: {len(sentences)}")
print("\nAll sentences:")
for i, sent in enumerate(sentences, 1):
    print(f"{i}. {sent}")

# Generate embeddings for all sentences
print("Generating embeddings...")
embeddings = model.encode(sentences)
print(f"Embeddings shape: {embeddings.shape}")  # Should be (10, 384)

# Compute cosine similarity matrix
print("Computing similarity matrix...")
similarity_matrix = cosine_similarity(embeddings)
print(f"Similarity matrix shape: {similarity_matrix.shape}")
print("\nFirst few similarity values:")
print(similarity_matrix[:3, :3])  # Print first 3x3

# Create and display heatmap
plt.figure(figsize=(14, 12))

# Create custom labels
labels = []
for i in range(len(sentences)):
    if i < 3:
        labels.append(f"Cricket_{i+1}")
    elif i < 7:
        labels.append(f"Cooking_{i-2}")
    else:
        labels.append(f"Security_{i-6}")

# Plot heatmap
sns.heatmap(
    similarity_matrix,
    annot=True,
    fmt='.3f',
    cmap='coolwarm',
    xticklabels=labels,
    yticklabels=labels,
    vmin=0,
    vmax=1,
    square=True,
    cbar_kws={"shrink": 0.8}
)

plt.title('Cosine Similarity Matrix of 10 Sentences\n(Cricket | Cooking | Cybersecurity)',
          fontsize=16, fontweight='bold')
plt.xlabel('Sentences', fontsize=12)
plt.ylabel('Sentences', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# Display similarity matrix as DataFrame for better readability
similarity_df = pd.DataFrame(
    similarity_matrix,
    index=[f"S{i+1}" for i in range(len(sentences))],
    columns=[f"S{i+1}" for i in range(len(sentences))]
)

print("Similarity Matrix as DataFrame:")
similarity_df

# Query sentence
query_sentence = "The bowler took three wickets in one over"
print(f"Query: '{query_sentence}'")
print("-" * 60)

# Generate embedding for the query
query_embedding = model.encode([query_sentence])

# Compute similarity with all sentences
similarities = cosine_similarity(query_embedding, embeddings)[0]

# Create results dataframe
results_df = pd.DataFrame({
    'Sentence #': range(1, len(sentences)+1),
    'Sentence': sentences,
    'Similarity Score': similarities,
    'Topic': ['Cricket']*3 + ['Cooking']*4 + ['Cybersecurity']*3
})

# Sort by similarity
results_df = results_df.sort_values('Similarity Score', ascending=False)
results_df = results_df.reset_index(drop=True)

print("\nAll sentences ranked by similarity:")
print(results_df)

print("\n" + "="*60)
print("TOP 2 MOST SIMILAR SENTENCES:")
print("="*60)

top_2 = results_df.head(2)
for idx, row in top_2.iterrows():
    print(f"\nRank #{idx+1}:")
    print(f"  Topic: {row['Topic']}")
    print(f"  Similarity Score: {row['Similarity Score']:.4f}")
    print(f"  Sentence: {row['Sentence']}")

# Analyze how well the embeddings capture topic separation
print("\n" + "="*60)
print("TOPIC SEPARATION ANALYSIS")
print("="*60)

# Group sentences by topic
topics = {
    'Cricket': sentences[0:3],
    'Cooking': sentences[3:7],
    'Cybersecurity': sentences[7:10]
}

# Calculate average intra-topic similarity
for topic, topic_sentences in topics.items():
    # Get indices of sentences for this topic
    topic_indices = [sentences.index(s) for s in topic_sentences]

    # Calculate average similarity within the topic
    intra_similarities = []
    for i in range(len(topic_indices)):
        for j in range(i+1, len(topic_indices)):
            intra_similarities.append(similarity_matrix[topic_indices[i], topic_indices[j]])

    if intra_similarities:
        avg_intra = np.mean(intra_similarities)
        print(f"\n{topic}:")
        print(f"  Average intra-topic similarity: {avg_intra:.4f}")

        # Calculate inter-topic similarity with other topics
        other_sentences = []
        for other_topic, other_sents in topics.items():
            if other_topic != topic:
                other_sentences.extend(other_sents)

        other_indices = [sentences.index(s) for s in other_sentences]
        inter_similarities = []
        for t_idx in topic_indices:
            for o_idx in other_indices:
                inter_similarities.append(similarity_matrix[t_idx, o_idx])

        if inter_similarities:
            avg_inter = np.mean(inter_similarities)
            print(f"  Average inter-topic similarity: {avg_inter:.4f}")
            print(f"  Topic separation score: {avg_intra - avg_inter:.4f}")

# Create bar chart for query similarity results
plt.figure(figsize=(12, 6))

# Color coding based on topic
colors = []
for sent in sentences:
    if sent in topics['Cricket']:
        colors.append('#FF6B6B')  # Red for Cricket
    elif sent in topics['Cooking']:
        colors.append('#4ECDC4')  # Teal for Cooking
    else:
        colors.append('#45B7D1')  # Blue for Cybersecurity

bars = plt.bar(range(len(sentences)), similarities, color=colors)

# Add labels and title
plt.xlabel('Sentence Number', fontsize=12)
plt.ylabel('Similarity Score', fontsize=12)
plt.title(f'Query: "{query_sentence}"\nSimilarity with All Sentences', fontsize=14)

# Add legend
from matplotlib.patches import Patch
legend_elements = [
    Patch(facecolor='#FF6B6B', label='Cricket'),
    Patch(facecolor='#4ECDC4', label='Cooking'),
    Patch(facecolor='#45B7D1', label='Cybersecurity')
]
plt.legend(handles=legend_elements, loc='upper right')

# Add value labels on bars
for i, (bar, score) in enumerate(zip(bars, similarities)):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,
             f'{score:.3f}', ha='center', va='bottom', fontsize=9)

plt.xticks(range(len(sentences)), [f'S{i+1}' for i in range(len(sentences))])
plt.ylim(0, 1.1)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

# Save the similarity matrix to CSV
similarity_df.to_csv('similarity_matrix.csv')
print("Similarity matrix saved to 'similarity_matrix.csv'")

# Save query results
results_df.to_csv('query_results.csv', index=False)
print("Query results saved to 'query_results.csv'")

# Download files (optional)
from google.colab import files
files.download('similarity_matrix.csv')
files.download('query_results.csv')